### ISSUE TITLE
同じ観測所名があると、ダウンロードがうまくいかない

### ISSUE THREAD

**Issue by KatsuhiroMorishita** [KatsuhiroMorishita/AMeDAS_downloader#2]
同じ観測所名に対応できていないことに気が付いた。
例：1462  高松, 47891   高松

IDで処理するように切り替えないと・・・。

**Comment by KenYMG** [comment]
同じ事象にあたりました。ご対応いただけるとありがたいです。
0951 府中,1133府中

**Comment by KatsuhiroMorishita** [comment]
そう言えば、このアメダス観測データをダウンロードするスクリプトを作った初期段階では同じ観測所を区別する作りにしていたんでした。最近になって最新の観測データも取得したいなと思って改造したときにはすっかり忘れていました。。。

人力以外の対策は思いついたのですが、丸一日改造に掛かりそうなので数日したら対応しようと思います。

**Comment by KatsuhiroMorishita** [comment]
バグを取ったつもりです。確認してみてください。

**Comment by KenYMG** [comment]
上手くいくようになりました。ありがとうございます。

**Comment by KatsuhiroMorishita** [comment]
報告ありがとうございます。では、このissueは閉めます。
