### ISSUE TITLE
html_parser.py がエラーとなって動作しません。

### ISSUE THREAD

**Issue by tanabata-kitajima** [KatsuhiroMorishita/AMeDAS_downloader#3]
html_parserを叩くと262行目でエラーとなります。

コードではblock_noという変数がありますが、この変数はほかの箇所では定義も使われてもいませんので、これが問題のように見えます。

**Comment by KatsuhiroMorishita** [comment]
ご指摘ありがとうございます。機能を増やしたつもりでバグを入れていました。。修正しました。
