### ISSUE TITLE
html_parser.pyでのエラー

### ISSUE THREAD

**Issue by kwsk708** [KatsuhiroMorishita/AMeDAS_downloader#5]
初めまして．便利に利用させていただいております．ありがとうございます．

日別のデータをダウンロードしたのち，html_parser.pyを実行すると

> Traceback (most recent call last):
  File "C:\Users\\AMeDAS_downloader-master\html_parser.py", line 411, in <module>
    main()
  File "C:\Users\\AMeDAS_downloader-master\html_parser.py", line 398, in main
    data = get_data(lines, _date)
  File "C:\Users\\AMeDAS_downloader-master\html_parser.py", line 329, in get_data
    if "時" in t: # 日時を1列目に加えるために、項目名を増やす
TypeError: argument of type 'int' is not iterable

となります．hourly，10minでは発生しないです．
ご確認いただけますと幸いです．

Windows10 Python3.7.4

**Comment by KatsuhiroMorishita** [comment]
エラー報告ありがとうございます。
ダウンロードした日時とアメダス観測点の情報を頂けますでしょうか？

**Comment by kwsk708** [comment]
ご返信ありがとうございます．
以下の通りです．
> start=2017,01,20
> stop=2017,01,25
> target=
> 1001	青梅

他の地点や期間で試しても発生しています．
初心者なもので，大変申し訳無いのですが，こちらの環境設定の問題でしょうか...
もしこちらの設定の方に心当たりがございましたらご教授いただければ幸いです．

**Comment by KatsuhiroMorishita** [comment]
私の方環境では再現しませんでした。プログラムのバージョンが最新か確認して頂いてもよろしいでしょうか？

**Comment by kwsk708** [comment]
確認いただきありがとうございました．
念のため，再度プログラムをダウンロードし，AMEDAS.iniを初期状態のままdailyでダウンロード，のちhtml_parser.pyを実行してみましたが，同様でしたので，こちらの問題のような気がします...
再度見直します．
お手数おかけしました．

**Comment by KatsuhiroMorishita** [comment]
Python 3.7.4の仮想環境を作って実行してみたら、エラーになりました(笑)
ライブラリのバージョンのせいかもしれません。
ちょっと確認します。

**Comment by KatsuhiroMorishita** [comment]
pandasの挙動が変わったみたいですね。
対応できたと思います。

**Comment by kwsk708** [comment]
正常に動作しました！
ご対応ありがとうございました．
